<?php

/**
 * Implementation of hook_views_api().
 */
function views_inputfield_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Gets our field if it exists on the passed-in view.
 *
 * @return
 *  The field object if found. Otherwise, FALSE.
 */
function views_inputfield_get_field($view) {
  foreach ($view->field as $field_name => $field) {
    if (is_a($field, 'views_inputfield_handler_field')) {
      // Add in the view object for convenience.
      $field->view = $view;
      return $field;
    }
  }
  return FALSE;
}

